services:
  - type: web
    name: smart-traffic-monitor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 120 --workers 2 app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: RENDER
        value: "true"
      - key: MODEL_PATH
        value: ./95_e/cls_fix_30e/weights/best.pt
      - key: CONFIDENCE_THRESHOLD
        value: "0.45"
      - key: FRAME_SKIP_RATE
        value: "5"
      - key: FLASK_DEBUG
        value: "false"
      - key: PYTHON_VERSION
        value: 3.11.6